# Generated by Django 4.2.2 on 2023-10-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='media',
            field=models.FileField(blank=True, upload_to='uploads/', verbose_name='Прикрепленные файлы'),
        ),
    ]
