# Generated by Django 5.0.1 on 2024-02-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mmorpg', '0004_alter_ads_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='accepted',
            field=models.BooleanField(default=False, verbose_name='Принят'),
        ),
        migrations.AlterField(
            model_name='response',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата отклика'),
        ),
        migrations.AlterField(
            model_name='response',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
